== Beispiel der Plantuml Diagrammerstellung

Plantuml Diagramme sind rein textbasierte Diagramme welche über das Framework plantuml in Grafikformate gewandelt
werden. Die textuale Beschreibung der Diagramme soll in diesem Beispiel nicht manuell sondern durch einen Builder
erfolgen. Die Definition eines Plantumldiagram lässt sich in diverse Bereiche wie Header, Footer, Objektdefinitionen,
Verbindungen zwischen Objekten etc. unterteilen.

Da die Bereiche in einer festgelegten Reihenfolge in der Diagrambeschreibung aufgeführt werden müssen, sollten
sich Stage basierte Builder besonders gut eignen. Die zu bildende Instanz ist im Prinzip ein Text, also eine Instanz
von String. Da bei der Programmierung der Konkatinierung von Strings lieber ein Stringbuilder vorgezogen werden sollte,
werden wir auch in diesem Beispiel statt eines Strings einen StringBuilder als zu buildende Instanz verwenden.

Die verwendbaren fachlichen Methoden wie addHeader etc. werden wir in den Stages definieren und immer auf die
append Methode des Stringbuilders abbilden. Es folgt eine Veranschaulichung eines Builders zum Erstellen eines
minimalen Plantuml Diagrammes.

Als Ergebnis gibt der Builder im Test folgende Diagramm Definition zurück:
[source]
.Generierte Plantuml Sourcen für ein Entity Diagram
----
@startuml
entity Mitarbeiter{
* id  varchar2(2000) <<PK>>
}
@enduml
----

Dieses kann online über folgenden URL ausprobiert und in eine Grafik umgewandelt werden:
https://www.plantuml.com/plantuml

Die zugehörigen Quellen sehen wie folgt aus:

[source,java]
.PlantumlEntityDiagramBuilder.java
----
include::../../main/java/com/github/huluvu424242/e3plantumldiagram/PlantumlEntityDiagramBuilder.java[lines=28..-1]
----

[source,java]
.BuilderStage.java
----
include::../../main/java/com/github/huluvu424242/e3plantumldiagram/BuilderStates.java[lines=28..-1]
----

[source,java]
.PlantumlEntityDiagramBuilderTest.java
----
include::../../test/java/com/github/huluvu424242/e3plantumldiagram/PlantumlEntityDiagramBuilderTest.java[lines=28..-1]
----


Weiter zum xref:4regex-statechart.adoc[Beispiel RegEx Statechart] oder zurück zum xref:2states-example.adoc[Beispiel mit Zuständen].