@startuml
!pragma layout smetana
[*] -up-> Zahl1: 0-9
Zahl1 --> Zahl1: 0-9
Zahl1 --> Plus: +
Zahl1: erste Zahl

Plus -> Zahl: 0-9
Zahl --> Zahl: 0-9
Plus <-- Zahl: +
Zahl --> [*]: =
Zahl: n-te Zahl
@enduml